import Link from "next/link";
import { useRouter } from "next/router";
import React, { useContext, useEffect, useMemo, useState } from "react";
import DataTable from "react-data-table-component";
import { MdOutlineClear } from "react-icons/md";

const dataSource = [
  {
    id: 1,
    recordedDate: "8/10/2022",
    patientName: "Dari Gemmill",
    interventionName: "Comedy|Drama|Romance",
    pharmaceuticalCare: "Drama|Romance",
    interventions: "Comedy|Drama",
    company: "Mybuzz",
  },
  {
    id: 2,
    recordedDate: "2/17/2023",
    patientName: "Thacher Richter",
    interventionName: "Action|Adventure|Drama|Romance|Western",
    pharmaceuticalCare: "Comedy",
    interventions: "Comedy|Drama|Romance",
    company: "Zava",
  },
  {
    id: 3,
    recordedDate: "9/30/2022",
    patientName: "Frederich Derdes",
    interventionName: "Comedy",
    pharmaceuticalCare: "Action|Sci-Fi",
    interventions: "Comedy",
    company: "Eayo",
  },
  {
    id: 4,
    recordedDate: "10/19/2022",
    patientName: "Arnie Spires",
    interventionName: "Documentary|Drama|Musical",
    pharmaceuticalCare: "(no genres listed)",
    interventions: "Drama|War",
    company: "Shufflester",
  },
  {
    id: 5,
    recordedDate: "10/1/2022",
    patientName: "Whittaker Kamena",
    interventionName: "Drama",
    pharmaceuticalCare: "Documentary",
    interventions: "Drama",
    company: "Trilith",
  },
  {
    id: 6,
    recordedDate: "4/11/2022",
    patientName: "Davy Artz",
    interventionName: "Children|Comedy",
    pharmaceuticalCare: "Action|Sci-Fi|Thriller|IMAX",
    interventions: "Drama",
    company: "Babbleblab",
  },
  {
    id: 7,
    recordedDate: "3/27/2022",
    patientName: "Harlan Stollsteimer",
    interventionName: "Musical",
    pharmaceuticalCare: "Comedy|Drama",
    interventions: "Drama|Thriller",
    company: "Edgeify",
  },
  {
    id: 8,
    recordedDate: "1/20/2023",
    patientName: "Cary McFarland",
    interventionName: "Drama|Romance",
    pharmaceuticalCare: "Action|Drama|Thriller|War",
    interventions: "Crime|Drama|Thriller",
    company: "Skiba",
  },
  {
    id: 9,
    recordedDate: "2/28/2023",
    patientName: "Lilly Biddles",
    interventionName: "Drama|War",
    pharmaceuticalCare: "Adventure|Animation|Children|Comedy|Fantasy",
    interventions: "Drama",
    company: "Roombo",
  },
  {
    id: 10,
    recordedDate: "8/8/2022",
    patientName: "Wilmer Vaan",
    interventionName: "Drama|War",
    pharmaceuticalCare: "Drama|Romance",
    interventions: "Drama|War",
    company: "Youopia",
  },
  {
    id: 11,
    recordedDate: "11/9/2022",
    patientName: "Forrest Lockyer",
    interventionName: "Drama",
    pharmaceuticalCare: "Action|Adventure|Thriller",
    interventions: "Drama|Fantasy|Horror|Thriller",
    company: "Flashpoint",
  },
  {
    id: 12,
    recordedDate: "11/27/2022",
    patientName: "Liva Murricanes",
    interventionName: "Action",
    pharmaceuticalCare: "Adventure|Comedy|Drama|Romance",
    interventions: "Comedy|Drama|Musical|Romance",
    company: "Jaxbean",
  },
  {
    id: 13,
    recordedDate: "9/23/2022",
    patientName: "Germain Truitt",
    interventionName: "Comedy",
    pharmaceuticalCare: "Documentary|War",
    interventions: "Action|Drama|Fantasy|Horror",
    company: "Feedfish",
  },
  {
    id: 14,
    recordedDate: "3/3/2023",
    patientName: "Filberte Carillo",
    interventionName: "Action|Horror",
    pharmaceuticalCare: "Comedy|Drama|Sci-Fi",
    interventions: "Comedy|Drama|Romance",
    company: "Miboo",
  },
  {
    id: 15,
    recordedDate: "9/3/2022",
    patientName: "Loralee O' Reagan",
    interventionName: "Drama",
    pharmaceuticalCare: "Comedy",
    interventions: "Drama",
    company: "Eadel",
  },
  {
    id: 16,
    recordedDate: "4/2/2022",
    patientName: "Martino Gregg",
    interventionName: "Drama|Romance|War",
    pharmaceuticalCare: "Action",
    interventions: "Comedy|Romance",
    company: "Tazzy",
  },
  {
    id: 17,
    recordedDate: "2/1/2023",
    patientName: "Yalonda Austwick",
    interventionName: "Comedy|Musical|Romance",
    pharmaceuticalCare: "Documentary",
    interventions: "Comedy|Musical|Romance",
    company: "Twitterbeat",
  },
  {
    id: 18,
    recordedDate: "3/17/2022",
    patientName: "Chancey Fandrey",
    interventionName: "Comedy|Romance",
    pharmaceuticalCare: "Comedy|Drama",
    interventions: "Drama|Thriller",
    company: "Bubbletube",
  },
  {
    id: 19,
    recordedDate: "12/2/2022",
    patientName: "Alvera Gunnell",
    interventionName: "Comedy",
    pharmaceuticalCare: "Drama|Romance|Sci-Fi",
    interventions: "Horror|Thriller",
    company: "Talane",
  },
  {
    id: 20,
    recordedDate: "1/19/2023",
    patientName: "Murry Cumberledge",
    interventionName: "Drama|Mystery|Thriller",
    pharmaceuticalCare: "Drama|Film-Noir|Mystery",
    interventions: "Drama|Romance",
    company: "Katz",
  },
  {
    id: 21,
    recordedDate: "6/19/2022",
    patientName: "Consuela Worling",
    interventionName: "Drama",
    pharmaceuticalCare: "Horror|Mystery",
    interventions: "Crime|Drama",
    company: "Linkbridge",
  },
  {
    id: 22,
    recordedDate: "11/14/2022",
    patientName: "Carny Petrelluzzi",
    interventionName: "Comedy",
    pharmaceuticalCare: "Drama|Romance|War",
    interventions: "Action|Animation|Fantasy|Sci-Fi",
    company: "Gigaclub",
  },
  {
    id: 23,
    recordedDate: "10/2/2022",
    patientName: "Noelle Knowller",
    interventionName: "Crime|Mystery",
    pharmaceuticalCare: "Comedy|Drama|Romance",
    interventions: "Western",
    company: "Demimbu",
  },
  {
    id: 24,
    recordedDate: "6/4/2022",
    patientName: "Rafael O'Keeffe",
    interventionName: "Action|Comedy",
    pharmaceuticalCare: "Documentary",
    interventions: "Documentary",
    company: "Edgeify",
  },
  {
    id: 25,
    recordedDate: "8/23/2022",
    patientName: "Henryetta Brimmacombe",
    interventionName: "Action|Crime|Drama|Thriller",
    pharmaceuticalCare: "Comedy|Horror",
    interventions: "Comedy|Horror",
    company: "Plambee",
  },
  {
    id: 26,
    recordedDate: "10/20/2022",
    patientName: "Miguel Bickerton",
    interventionName: "Crime|Drama",
    pharmaceuticalCare: "Comedy|Drama|Romance",
    interventions: "Drama",
    company: "Yodoo",
  },
  {
    id: 27,
    recordedDate: "10/18/2022",
    patientName: "Ashlin Duinbleton",
    interventionName: "Comedy",
    pharmaceuticalCare: "Documentary",
    interventions: "Adventure|Mystery|Western",
    company: "Abatz",
  },
  {
    id: 28,
    recordedDate: "6/17/2022",
    patientName: "Melva Jennings",
    interventionName: "Action|Adventure|Drama",
    pharmaceuticalCare: "Comedy",
    interventions: "Action|Adventure|Animation|Children|Comedy|IMAX",
    company: "Twitterbridge",
  },
  {
    id: 29,
    recordedDate: "7/25/2022",
    patientName: "Lonnard Hinkens",
    interventionName: "Comedy|Drama|Romance",
    pharmaceuticalCare: "Comedy|Fantasy|Musical",
    interventions: "Drama",
    company: "Riffpedia",
  },
  {
    id: 30,
    recordedDate: "7/5/2022",
    patientName: "Siobhan Gurner",
    interventionName: "Fantasy|Horror",
    pharmaceuticalCare: "Adventure|Children|Comedy|Fantasy",
    interventions: "Documentary|Musical",
    company: "InnoZ",
  },
  {
    id: 31,
    recordedDate: "2/4/2023",
    patientName: "Lorant Craigie",
    interventionName: "Drama",
    pharmaceuticalCare: "Drama",
    interventions: "Comedy",
    company: "Agivu",
  },
  {
    id: 32,
    recordedDate: "10/12/2022",
    patientName: "Carita Charlson",
    interventionName: "Comedy|Crime",
    pharmaceuticalCare: "Drama",
    interventions: "Action|Comedy",
    company: "Gigazoom",
  },
  {
    id: 33,
    recordedDate: "8/3/2022",
    patientName: "Lynnell Copp",
    interventionName: "Adventure|Children|Comedy",
    pharmaceuticalCare: "Drama|Romance",
    interventions: "Action|Crime|Thriller|IMAX",
    company: "Eare",
  },
  {
    id: 34,
    recordedDate: "6/9/2022",
    patientName: "Bonnie Ridgeway",
    interventionName: "Comedy|Drama",
    pharmaceuticalCare: "Comedy|Drama",
    interventions: "Drama|Fantasy|Romance",
    company: "Dynazzy",
  },
  {
    id: 35,
    recordedDate: "12/17/2022",
    patientName: "Ewen Mathet",
    interventionName: "Comedy",
    pharmaceuticalCare: "Drama",
    interventions: "Comedy|Drama|Romance",
    company: "Jayo",
  },
  {
    id: 36,
    recordedDate: "3/1/2023",
    patientName: "Jane Sidey",
    interventionName: "Drama",
    pharmaceuticalCare: "Drama|Horror|Romance",
    interventions: "Drama|Romance|War",
    company: "Skalith",
  },
  {
    id: 37,
    recordedDate: "7/24/2022",
    patientName: "Shane Gruszecki",
    interventionName: "Drama|War",
    pharmaceuticalCare: "Drama|Romance",
    interventions: "Drama",
    company: "Wikido",
  },
  {
    id: 38,
    recordedDate: "4/16/2022",
    patientName: "Cordy Raulin",
    interventionName: "Crime|Drama|Romance",
    pharmaceuticalCare: "Comedy",
    interventions: "Drama|Romance",
    company: "Janyx",
  },
  {
    id: 39,
    recordedDate: "12/8/2022",
    patientName: "Giselle Yanuk",
    interventionName: "Action|Fantasy|Horror|Thriller",
    pharmaceuticalCare: "Fantasy",
    interventions: "Comedy|Horror|Mystery|Sci-Fi",
    company: "JumpXS",
  },
  {
    id: 40,
    recordedDate: "9/11/2022",
    patientName: "Errol Allott",
    interventionName: "Drama|Romance",
    pharmaceuticalCare: "Comedy",
    interventions: "Drama",
    company: "Dabjam",
  },
  {
    id: 41,
    recordedDate: "7/12/2022",
    patientName: "Molly Rameaux",
    interventionName: "Drama",
    pharmaceuticalCare: "Adventure|Drama|Thriller",
    interventions: "Action",
    company: "Dabfeed",
  },
  {
    id: 42,
    recordedDate: "11/27/2022",
    patientName: "Tremayne Althrop",
    interventionName: "Comedy",
    pharmaceuticalCare: "Crime|Documentary",
    interventions: "Crime|Film-Noir|Mystery|Thriller",
    company: "Quaxo",
  },
  {
    id: 43,
    recordedDate: "12/16/2022",
    patientName: "Libbie Tampen",
    interventionName: "Drama|War",
    pharmaceuticalCare: "Action|Adventure|Comedy|Fantasy",
    interventions: "Documentary|Drama",
    company: "Voonte",
  },
  {
    id: 44,
    recordedDate: "3/10/2022",
    patientName: "Arni Burwood",
    interventionName: "Drama",
    pharmaceuticalCare: "Action|Sci-Fi|Thriller",
    interventions: "Drama|Romance",
    company: "Roomm",
  },
  {
    id: 45,
    recordedDate: "12/3/2022",
    patientName: "Brittni Glassborow",
    interventionName: "Drama",
    pharmaceuticalCare: "Drama",
    interventions: "Documentary",
    company: "Cogibox",
  },
  {
    id: 46,
    recordedDate: "3/27/2022",
    patientName: "Tallie Scutchin",
    interventionName: "Action|Comedy",
    pharmaceuticalCare: "Comedy",
    interventions: "Adventure|Animation|Comedy|Fantasy|IMAX",
    company: "Twitterlist",
  },
  {
    id: 47,
    recordedDate: "8/30/2022",
    patientName: "Tricia Whittick",
    interventionName: "Comedy|Crime|Drama",
    pharmaceuticalCare: "Crime|Drama|War",
    interventions: "Children|Comedy|Musical",
    company: "Innotype",
  },
  {
    id: 48,
    recordedDate: "7/30/2022",
    patientName: "Elsworth McKeaney",
    interventionName: "Crime|Mystery",
    pharmaceuticalCare: "Documentary",
    interventions: "Documentary",
    company: "Jaxspan",
  },
  {
    id: 49,
    recordedDate: "9/16/2022",
    patientName: "Powell Joskowitz",
    interventionName: "Comedy|Drama",
    pharmaceuticalCare: "Comedy|Romance",
    interventions: "Drama|Romance|War",
    company: "Youfeed",
  },
  {
    id: 50,
    recordedDate: "6/24/2022",
    patientName: "Jody Radborne",
    interventionName: "Comedy",
    pharmaceuticalCare: "Drama",
    interventions: "Drama",
    company: "Brightdog",
  },
  {
    id: 51,
    recordedDate: "3/15/2022",
    patientName: "Sonnie McCoughan",
    interventionName: "Horror",
    pharmaceuticalCare: "Romance",
    interventions: "Drama",
    company: "Realbridge",
  },
  {
    id: 52,
    recordedDate: "5/10/2022",
    patientName: "Cecilia Sive",
    interventionName: "Crime|Drama|Film-Noir|Mystery",
    pharmaceuticalCare: "Drama",
    interventions: "Comedy|Drama",
    company: "Snaptags",
  },
  {
    id: 53,
    recordedDate: "2/27/2023",
    patientName: "Dniren Skarin",
    interventionName: "Action|Adventure|Thriller",
    pharmaceuticalCare: "Action|Romance",
    interventions: "Drama",
    company: "Kwilith",
  },
  {
    id: 54,
    recordedDate: "6/10/2022",
    patientName: "Aurea Fawley",
    interventionName: "Drama",
    pharmaceuticalCare: "Drama",
    interventions: "Action|Sci-Fi|Thriller",
    company: "Brainverse",
  },
  {
    id: 55,
    recordedDate: "11/17/2022",
    patientName: "Jamison Treversh",
    interventionName: "Comedy|Drama",
    pharmaceuticalCare: "Crime|Film-Noir",
    interventions: "Animation|Children|Musical",
    company: "Kamba",
  },
  {
    id: 56,
    recordedDate: "1/2/2023",
    patientName: "Sebastian Lesor",
    interventionName: "(no genres listed)",
    pharmaceuticalCare: "Drama",
    interventions: "Comedy",
    company: "Feedbug",
  },
  {
    id: 57,
    recordedDate: "9/2/2022",
    patientName: "Ladonna Caccavale",
    interventionName: "Action|Comedy|Sci-Fi|IMAX",
    pharmaceuticalCare: "Drama",
    interventions: "Comedy|Horror|Thriller",
    company: "Photobug",
  },
  {
    id: 58,
    recordedDate: "9/29/2022",
    patientName: "Brit Goodanew",
    interventionName: "Drama",
    pharmaceuticalCare: "Action|Horror|Thriller",
    interventions: "Comedy",
    company: "Tanoodle",
  },
  {
    id: 59,
    recordedDate: "1/12/2023",
    patientName: "Marybeth McGavigan",
    interventionName: "(no genres listed)",
    pharmaceuticalCare: "Comedy",
    interventions: "Comedy",
    company: "Zooveo",
  },
  {
    id: 60,
    recordedDate: "3/3/2023",
    patientName: "Salomo Hearnden",
    interventionName: "Comedy|Romance",
    pharmaceuticalCare: "Western",
    interventions: "Comedy|Drama",
    company: "JumpXS",
  },
  {
    id: 61,
    recordedDate: "4/4/2022",
    patientName: "Luther Marcussen",
    interventionName: "Action|Adventure|Thriller",
    pharmaceuticalCare: "Comedy",
    interventions: "Adventure|Animation|Children",
    company: "Vidoo",
  },
  {
    id: 62,
    recordedDate: "11/20/2022",
    patientName: "Karalynn Sauven",
    interventionName: "Comedy|Horror|Thriller",
    pharmaceuticalCare: "Comedy|Crime|Drama|Western",
    interventions: "Action|Romance|Thriller",
    company: "Avamm",
  },
  {
    id: 63,
    recordedDate: "5/6/2022",
    patientName: "Abagail Pestridge",
    interventionName: "Drama",
    pharmaceuticalCare: "Animation|Documentary",
    interventions: "Documentary",
    company: "Riffpedia",
  },
  {
    id: 64,
    recordedDate: "9/10/2022",
    patientName: "Kristal Puddin",
    interventionName: "Documentary",
    pharmaceuticalCare: "Children|Comedy",
    interventions: "Crime|Drama|Romance|Thriller",
    company: "Eadel",
  },
  {
    id: 65,
    recordedDate: "10/26/2022",
    patientName: "Callida Lambden",
    interventionName: "Drama",
    pharmaceuticalCare: "Comedy",
    interventions: "Comedy|Romance",
    company: "Buzzster",
  },
  {
    id: 66,
    recordedDate: "1/13/2023",
    patientName: "Bridget Rossetti",
    interventionName: "Comedy|Drama",
    pharmaceuticalCare: "Action|Adventure|Sci-Fi",
    interventions: "Drama",
    company: "Abatz",
  },
  {
    id: 67,
    recordedDate: "8/4/2022",
    patientName: "Calla Harower",
    interventionName: "Drama",
    pharmaceuticalCare: "Documentary",
    interventions: "Drama",
    company: "Brainbox",
  },
  {
    id: 68,
    recordedDate: "5/26/2022",
    patientName: "Dulciana Kilpatrick",
    interventionName: "Adventure|Crime|Documentary",
    pharmaceuticalCare: "Drama|Romance",
    interventions: "Adventure",
    company: "Fiveclub",
  },
  {
    id: 69,
    recordedDate: "4/24/2022",
    patientName: "Lexy Werndly",
    interventionName: "Drama|Film-Noir",
    pharmaceuticalCare: "Comedy|Fantasy",
    interventions: "Drama",
    company: "Ooba",
  },
  {
    id: 70,
    recordedDate: "10/6/2022",
    patientName: "Essie Tyhurst",
    interventionName: "Drama|Fantasy|Romance",
    pharmaceuticalCare: "Drama",
    interventions: "Drama|Romance|Sci-Fi",
    company: "Shufflebeat",
  },
  {
    id: 71,
    recordedDate: "2/4/2023",
    patientName: "Olivie Gounod",
    interventionName: "Crime|Drama",
    pharmaceuticalCare: "Documentary",
    interventions: "Action|Horror|Thriller",
    company: "Tagcat",
  },
  {
    id: 72,
    recordedDate: "2/9/2023",
    patientName: "Victoria Skett",
    interventionName: "Comedy|War|Western",
    pharmaceuticalCare: "Drama|Mystery|Thriller",
    interventions: "Thriller",
    company: "Bubblemix",
  },
  {
    id: 73,
    recordedDate: "2/27/2023",
    patientName: "Florentia Wetherald",
    interventionName: "Comedy|Drama",
    pharmaceuticalCare: "Drama",
    interventions: "Crime|Drama|Thriller",
    company: "Digitube",
  },
  {
    id: 74,
    recordedDate: "10/28/2022",
    patientName: "Tommy Ribbon",
    interventionName: "Action|Sci-Fi",
    pharmaceuticalCare: "Fantasy|Horror|Thriller",
    interventions: "Crime|Drama",
    company: "Meevee",
  },
  {
    id: 75,
    recordedDate: "3/22/2022",
    patientName: "Obadiah Labuschagne",
    interventionName: "Comedy|Horror|Thriller",
    pharmaceuticalCare: "Crime|Thriller",
    interventions: "Action|Drama|Romance",
    company: "Thoughtbridge",
  },
  {
    id: 76,
    recordedDate: "4/21/2022",
    patientName: "Benita Ogle",
    interventionName: "Horror|Sci-Fi",
    pharmaceuticalCare: "Comedy",
    interventions: "Documentary",
    company: "Browsedrive",
  },
  {
    id: 77,
    recordedDate: "6/13/2022",
    patientName: "Tommy Leveritt",
    interventionName: "Documentary",
    pharmaceuticalCare: "Horror",
    interventions: "Documentary",
    company: "Blogtag",
  },
  {
    id: 78,
    recordedDate: "3/24/2022",
    patientName: "Marchall Wiltshier",
    interventionName: "Action|Adventure|Comedy",
    pharmaceuticalCare: "Comedy|Drama|Fantasy",
    interventions: "Sci-Fi",
    company: "Midel",
  },
  {
    id: 79,
    recordedDate: "10/21/2022",
    patientName: "Dory Laverock",
    interventionName: "Horror",
    pharmaceuticalCare: "Drama",
    interventions: "Comedy",
    company: "Skiba",
  },
  {
    id: 80,
    recordedDate: "10/10/2022",
    patientName: "Bern Drever",
    interventionName: "Documentary",
    pharmaceuticalCare: "Drama",
    interventions: "Comedy|Horror",
    company: "LiveZ",
  },
  {
    id: 81,
    recordedDate: "3/5/2023",
    patientName: "Zollie Licciardo",
    interventionName: "Thriller",
    pharmaceuticalCare: "Crime|Drama|Thriller",
    interventions: "Adventure|Animation",
    company: "Skaboo",
  },
  {
    id: 82,
    recordedDate: "10/26/2022",
    patientName: "Lilly Plank",
    interventionName: "Horror|Mystery|Thriller",
    pharmaceuticalCare: "Action|Crime|Thriller",
    interventions: "Comedy",
    company: "Vinder",
  },
  {
    id: 83,
    recordedDate: "4/7/2022",
    patientName: "Guinevere Kiss",
    interventionName: "Comedy|War",
    pharmaceuticalCare: "Comedy|Horror",
    interventions: "Children|Comedy|Musical",
    company: "Gabtype",
  },
  {
    id: 84,
    recordedDate: "6/25/2022",
    patientName: "Gerda Gwilt",
    interventionName: "Comedy",
    pharmaceuticalCare: "Drama",
    interventions: "Drama",
    company: "Devcast",
  },
  {
    id: 85,
    recordedDate: "5/11/2022",
    patientName: "Alla Findlay",
    interventionName: "Adventure|Drama|Thriller",
    pharmaceuticalCare: "Horror",
    interventions: "Drama|Fantasy|Romance",
    company: "Feednation",
  },
  {
    id: 86,
    recordedDate: "4/23/2022",
    patientName: "Merla Ballendine",
    interventionName: "Drama",
    pharmaceuticalCare: "Children|Drama|Fantasy|Musical",
    interventions: "Comedy|Drama",
    company: "Zooveo",
  },
  {
    id: 87,
    recordedDate: "2/20/2023",
    patientName: "Udall McArthur",
    interventionName: "Action|Thriller",
    pharmaceuticalCare: "Comedy",
    interventions: "Drama|Fantasy|Romance",
    company: "Rhybox",
  },
  {
    id: 88,
    recordedDate: "1/29/2023",
    patientName: "Wynnie Van Dalen",
    interventionName: "Drama|Film-Noir|Musical|Thriller",
    pharmaceuticalCare: "(no genres listed)",
    interventions: "Comedy|Drama|Musical|Romance",
    company: "Rhynyx",
  },
  {
    id: 89,
    recordedDate: "4/23/2022",
    patientName: "Darnall Bunker",
    interventionName: "Horror|Thriller",
    pharmaceuticalCare: "Drama",
    interventions: "Drama",
    company: "Skilith",
  },
  {
    id: 90,
    recordedDate: "3/30/2022",
    patientName: "Nevin Haire",
    interventionName: "Drama",
    pharmaceuticalCare: "Documentary",
    interventions: "Drama|Romance|War",
    company: "Jabbersphere",
  },
  {
    id: 91,
    recordedDate: "5/20/2022",
    patientName: "Alie Shields",
    interventionName: "Drama",
    pharmaceuticalCare: "Action|Thriller|War",
    interventions: "Comedy|Documentary|Musical",
    company: "Brightbean",
  },
  {
    id: 92,
    recordedDate: "1/14/2023",
    patientName: "Biddie Mellodey",
    interventionName: "Drama",
    pharmaceuticalCare: "Documentary",
    interventions: "Animation|Children",
    company: "Fivebridge",
  },
  {
    id: 93,
    recordedDate: "6/4/2022",
    patientName: "Caroline Gallifont",
    interventionName: "Western",
    pharmaceuticalCare: "Drama",
    interventions: "Crime|Film-Noir|Mystery|Thriller",
    company: "Skinte",
  },
  {
    id: 94,
    recordedDate: "10/23/2022",
    patientName: "Davey Viollet",
    interventionName: "Romance|Western",
    pharmaceuticalCare: "Horror|Thriller",
    interventions: "Comedy|Drama|Romance",
    company: "Fivechat",
  },
  {
    id: 95,
    recordedDate: "8/15/2022",
    patientName: "Britta Yellep",
    interventionName: "Horror",
    pharmaceuticalCare: "Animation|Comedy|Drama|Fantasy",
    interventions: "Drama",
    company: "Zazio",
  },
  {
    id: 96,
    recordedDate: "6/30/2022",
    patientName: "Aldo Vinden",
    interventionName: "Horror|War|Western",
    pharmaceuticalCare: "Romance",
    interventions: "Romance",
    company: "Meeveo",
  },
  {
    id: 97,
    recordedDate: "12/19/2022",
    patientName: "Lisbeth Strewther",
    interventionName: "Adventure|Crime|Drama",
    pharmaceuticalCare: "Sci-Fi",
    interventions: "Drama",
    company: "Voonte",
  },
  {
    id: 98,
    recordedDate: "1/3/2023",
    patientName: "Galven Filgate",
    interventionName: "Comedy|Drama|Musical",
    pharmaceuticalCare: "Comedy|Drama|Romance",
    interventions: "Thriller",
    company: "Fadeo",
  },
  {
    id: 99,
    recordedDate: "11/29/2022",
    patientName: "Derrek Geerits",
    interventionName: "Sci-Fi",
    pharmaceuticalCare: "Comedy",
    interventions: "Drama|Musical|Romance|IMAX",
    company: "Livepath",
  },
  {
    id: 100,
    recordedDate: "7/6/2022",
    patientName: "Gibb Pilger",
    interventionName: "Comedy|Crime",
    pharmaceuticalCare: "Comedy|Romance",
    interventions: "Animation|Comedy",
    company: "Browsezoom",
  },
];

const FilterComponent = ({ filterText, onFilter, onClear }) => (
  <div className="flex flex-row h-8 bg-transparent !important ">
    <input
      id="search"
      type="text"
      placeholder="Filter By Name"
      value={filterText}
      onChange={onFilter}
      className="p-2 rounded outline-none"
    />
    <button onClick={onClear} className="bg-[#800020] p-2 text-white h-full">
      <MdOutlineClear />
    </button>
  </div>
);

const MyInterventions = () => {
  const router = useRouter();

  const handleRowClicked = (row) => {
    // Navigate to the details page with the clicked row's ID as a query parameter
    router.push(`/user/${row.id}`);
  };

  const [data, setData] = useState(dataSource);
  const [filterText, setFilterText] = useState("");
  const [resetPaginationToggle, setResetPaginationToggle] = useState(false);
  const filteredItems = data.filter(
    (item) =>
      item.patientName &&
      item.patientName.toLowerCase().includes(filterText.toLowerCase())
  );

  const subHeaderComponentMemo = useMemo(() => {
    const handleClear = () => {
      if (filterText) {
        setResetPaginationToggle(!resetPaginationToggle);
        setFilterText("");
      }
    };

    return (
      <FilterComponent
        onFilter={(e) => setFilterText(e.target.value)}
        onClear={handleClear}
        filterText={filterText}
      />
    );
  }, [filterText, resetPaginationToggle]);

  const columns = [
    {
      name: "Recorded Date",
      selector: (row) => row.recordedDate,
      sortable: true,
    },
    {
      name: "Patient Name",
      selector: (row) => row.patientName,
      sortable: true,
    },
    {
      name: "Intervention ID",
      selector: (row) => row.interventionName,
      sortable: true,
    },
    {
      name: "Pharmaceutical Care",
      selector: (row) => row.pharmaceuticalCare,
      sortable: true,
    },
    {
      name: "Interventions",
      selector: (row) => row.interventions,
      sortable: true,
    },
    {
      name: "Company",
      selector: (row) => row.company,
      sortable: true,
    },
  ];

  return (
    <>
      <div className="flex flex-col justify-center w-full gap-5 px-5 py-5 mx-auto ">
        <div className="flex justify-between gap-3">
          <Link
            href="/addIntervention"
            className=" text-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
          >
            Add Intervention
          </Link>
          <Link
            href="/"
            className="text-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
          >
            Go Home
          </Link>
        </div>
      </div>
      <div className="flex flex-col justify-center w-full px-5 py-2 mx-auto shadow-xl ">
        <DataTable
          columns={columns}
          data={filteredItems}
          pagination
          paginationResetDefaultPage={resetPaginationToggle} // optionally, a hook to reset pagination to page 1
          subHeader
          subHeaderComponent={subHeaderComponentMemo}
          selectableRows={false}
          persistTableHead
          onRowClicked={handleRowClicked}
        />
      </div>
    </>
  );
};

export default MyInterventions;
